version: "3.9"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
    container_name: rtmp_server
  server:
    build: ./BitirmeTezi
    ports:
      - "5000:80"
    container_name : bitirme_server
    